### ISSUE TITLE
Does not work properly

### ISSUE THREAD

**Issue by xjjrocker** [codydbentley/wails-vite-vue-ts#2]
Follow the steps in order：
1、`wails init -n myWailsVueTs -t https://github.com/codydbentley/wails-vite-vue-ts`
2、`cd myWailsVueTs`
3、`wails dev`
Then the following error is displayed:
```
ERROR: 
main.go:13:12: pattern frontend/dist: cannot embed directory frontend/dist: contains no embeddable files

exit status 1
```

**Comment by PungYoung** [comment]
> 
cd frontend
npm run dev

# new tab
wails dev
it is work
